import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { formatCurrency } from "@/lib/utils";

interface SalesManagerPerformanceProps { salesManagerId: string; performance: { ytdTarget: number; ytdAchievement: number; ytdRate: number; avgTicketSize: number; conversionRate: number; customerSatisfaction: number; monthlyHistory: { month: string; target: number; achievement: number; rate: number }[]; }; }

export function SalesManagerPerformance({ performance }: SalesManagerPerformanceProps) {
  const stats = [["YTD achievement", `${performance.ytdRate}%`], ["YTD production", formatCurrency(performance.ytdAchievement)], ["Average ticket", formatCurrency(performance.avgTicketSize)], ["Conversion rate", `${performance.conversionRate}%`], ["Customer satisfaction", `${performance.customerSatisfaction}/5`]];
  return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{stats.map(([label, value]) => <Card key={label}><CardContent className="p-5"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></CardContent></Card>)}</div><Card><CardHeader><CardTitle className="text-base">Monthly performance</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[480px] text-left text-sm"><thead className="border-b text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="pb-3">Month</th><th className="pb-3">Target</th><th className="pb-3">Achievement</th><th className="pb-3">Rate</th></tr></thead><tbody>{performance.monthlyHistory.map((month) => <tr key={month.month} className="border-b border-slate-100 last:border-0"><td className="py-3 font-medium">{month.month}</td><td className="py-3">{formatCurrency(month.target)}</td><td className="py-3">{formatCurrency(month.achievement)}</td><td className="py-3 font-medium">{month.rate}%</td></tr>)}</tbody></table></CardContent></Card></div>;
}
